[template.environment]
#Variables for Contentful
CONTENTFUL_SPACE_ID = "CONTENTFUL_SPACE_ID"
CONTENTFUL_ACCESS_TOKEN = "CONTENTFUL_ACCESS_TOKEN"
CONTENTFUL_REVALIDATE_SECRET = "CONTENTFUL_REVALIDATE_SECRET"
CONTENTFUL_MANAGEMENT_TOKEN = "CONTENTFUL_MANAGEMENT_TOKEN"
#Variables for Netlify
NETLIFY_API_TOKEN = "NETLIFY_API_TOKEN"
NETLIFY_TEAM_SLUG = "NETLIFY_TEAM_SLUG"


[[plugins]]
package = "/plugins/contentful-setup"
