[template.environment]
CONTENTFUL_SPACE_ID = "Found under Settings > General Settings"
CONTENTFUL_ACCESS_TOKEN = "Found under Settings > Api Keys"
CONTENTFUL_REVALIDATE_SECRET = "Generate any random value you wish"
CONTENTFUL_MANAGEMENT_TOKEN = "Found under Settings > Api Keys"
